import assert from 'node:assert/strict';
import test from 'node:test';
import { setupFulfillment } from '../helpers/fulfillment-fixture.mjs';

test('Case A: concurrent payment has one record, audit, correct amount and stable retry',async()=>{const c=await setupFulfillment();try{const [a,b]=await Promise.all([c.service.confirmPayment('a','A','O1'),c.service.confirmPayment('a','A','O1')]);assert.equal(a.finalPayableMinor,600);assert.equal(b.paymentStatus,'paid');assert.equal(c.db.database.prepare("SELECT COUNT(*) n FROM cash_payments WHERE order_id='O1'").get().n,1);assert.equal(c.db.database.prepare("SELECT COUNT(*) n FROM audit_logs WHERE metadata LIKE '%CASH_PAYMENT_CONFIRMED%'").get().n,1);}finally{c.db.close();}});
test('Case B: concurrent handover has one transition and audit',async()=>{const c=await setupFulfillment();try{await c.service.confirmPayment('a','A','O1');const [a,b]=await Promise.all([c.service.confirmHandover('a','A','O1'),c.service.confirmHandover('a','A','O1')]);assert.equal(a.pickupStatus,'handed_over');assert.equal(b.pickupStatus,'handed_over');assert.equal(c.db.database.prepare("SELECT COUNT(*) n FROM audit_logs WHERE metadata LIKE '%ORDER_HANDED_OVER%'").get().n,1);}finally{c.db.close();}});
test('Case C: payment and handover race never produces unpaid handed over',async()=>{const c=await setupFulfillment();try{await Promise.allSettled([c.service.confirmPayment('a','A','O1'),c.service.confirmHandover('a','A','O1')]);const row=await c.service.get('a','A','O1');assert.equal(row.paymentStatus,'paid');assert.ok(['pending','handed_over'].includes(row.pickupStatus));}finally{c.db.close();}});
test('Case D: different orders complete independently',async()=>{const c=await setupFulfillment();try{await Promise.all([c.service.confirmPayment('a','A','O1'),c.service.confirmPayment('a','X','OX')]);await Promise.all([c.service.confirmHandover('a','A','O1'),c.service.confirmHandover('a','X','OX')]);assert.equal((await c.service.get('a','A','O1')).completionState,'completed');assert.equal((await c.service.get('a','X','OX')).completionState,'completed');}finally{c.db.close();}});
test('Case E: retries preserve payment and handover timestamps',async()=>{const c=await setupFulfillment();try{await c.service.confirmPayment('a','A','O1');const paidAt=c.db.database.prepare("SELECT confirmed_at FROM cash_payments WHERE order_id='O1'").get().confirmed_at;await c.service.confirmPayment('a','A','O1');assert.equal(c.db.database.prepare("SELECT confirmed_at FROM cash_payments WHERE order_id='O1'").get().confirmed_at,paidAt);await c.service.confirmHandover('a','A','O1');const handedAt=c.db.database.prepare("SELECT picked_up_at FROM pickup_records WHERE order_id='O1'").get().picked_up_at;await c.service.confirmHandover('a','A','O1');assert.equal(c.db.database.prepare("SELECT picked_up_at FROM pickup_records WHERE order_id='O1'").get().picked_up_at,handedAt);}finally{c.db.close();}});
test('payment audit failure rolls back payment and pickup',async()=>{const c=await setupFulfillment();try{c.db.exec("CREATE TRIGGER reject_payment_audit BEFORE INSERT ON audit_logs WHEN NEW.metadata LIKE '%CASH_PAYMENT_CONFIRMED%' BEGIN SELECT RAISE(ABORT,'TEST_AUDIT_FAILURE'); END");await assert.rejects(c.service.confirmPayment('a','A','O1'),/TEST_AUDIT_FAILURE/);assert.equal(c.db.database.prepare("SELECT COUNT(*) n FROM cash_payments WHERE order_id='O1'").get().n,0);assert.equal(c.db.database.prepare("SELECT COUNT(*) n FROM pickup_records WHERE order_id='O1'").get().n,0);}finally{c.db.close();}});
test('handover audit failure rolls back handover',async()=>{const c=await setupFulfillment();try{await c.service.confirmPayment('a','A','O1');c.db.exec("CREATE TRIGGER reject_handover_audit BEFORE INSERT ON audit_logs WHEN NEW.metadata LIKE '%ORDER_HANDED_OVER%' BEGIN SELECT RAISE(ABORT,'TEST_AUDIT_FAILURE'); END");await assert.rejects(c.service.confirmHandover('a','A','O1'),/TEST_AUDIT_FAILURE/);const pickup=c.db.database.prepare("SELECT status,picked_up_at FROM pickup_records WHERE order_id='O1'").get();assert.equal(pickup.status,'ready');assert.equal(pickup.picked_up_at,null);}finally{c.db.close();}});
