import assert from 'node:assert/strict';
import test from 'node:test';
import { Repositories } from '../../server/repositories/index.ts';
import { OrderService,PickupService } from '../../server/services/orders.ts';
import { CommunityMembershipService } from '../../server/services/index.ts';
import { createPhase4BDatabase,seed } from '../helpers/sqlite-database.mjs';

async function setup(){const db=await createPhase4BDatabase();seed(db,`INSERT INTO users(id) VALUES ('u'),('admin');INSERT INTO user_profiles(user_id,display_name,phone) VALUES ('u','住戶','0900000000'),('admin','管理員','0900000001');INSERT INTO communities(id,name,slug) VALUES ('A','A','a');INSERT INTO community_members(id,user_id,community_id,role) VALUES ('mu','u','A','resident'),('ma','admin','A','community_admin');INSERT INTO products(id,name,source_type,unit_label) VALUES ('p1','米','manual','包'),('p2','油','supplier','瓶');INSERT INTO community_product_offerings(id,community_id,product_id,price_minor,batch_threshold,min_quantity_per_order) VALUES ('o1','A','p1',1000,30,1),('o2','A','p2',500,2,1);`);const repositories=new Repositories({db});return{db,repositories,orders:new OrderService(repositories),pickups:new PickupService(repositories)};}

test('order create、items FK、snapshot、commitment linkage 與 total',async()=>{const c=await setup();const result=await c.orders.create('u',{communityId:'A',idempotencyKey:'order-key-001',items:[{offeringId:'o1',quantity:3},{offeringId:'o2',quantity:2}]});assert.equal(result.created,true);assert.equal(result.order.estimatedTotalMinor,4000);assert.deepEqual(new Set(result.order.items.map(x=>x.product_name_snapshot)),new Set(['米','油']));const report=await c.repositories.reconciliation.inspect(result.order.id);assert.equal(report.ok,true);await assert.rejects(()=>c.repositories.batch([c.repositories.orders.insertItemStatement({id:'bad',orderId:'missing',offeringId:'o1',productId:'p1',productName:'米',unitLabel:'包',unitPrice:1,quantity:1})]),/FOREIGN KEY/);c.db.close();});
test('idempotency unique 且相同 key 回傳原 order',async()=>{const c=await setup();const input={communityId:'A',idempotencyKey:'same-key-001',items:[{offeringId:'o1',quantity:1}]};const a=await c.orders.create('u',input),b=await c.orders.create('u',input);assert.equal(a.order.id,b.order.id);assert.equal((await c.repositories.orders.listForUser('u')).length,1);c.db.close();});
test('multi-item allocation failure 整張 rollback',async()=>{const c=await setup();await assert.rejects(()=>c.orders.create('u',{communityId:'A',idempotencyKey:'rollback-001',items:[{offeringId:'o1',quantity:1},{offeringId:'missing',quantity:1}]}));assert.equal((await c.repositories.orders.listForUser('u')).length,0);assert.equal((await c.repositories.batches.listForOffering('o1')).length,0);c.db.close();});
test('admin cancellation 釋放 commitment、重算 formed→open 並保存 audit',async()=>{const c=await setup();const created=await c.orders.create('u',{communityId:'A',idempotencyKey:'cancel-001',items:[{offeringId:'o1',quantity:30}]});await c.orders.cancel('admin',created.order.id,'住戶申請','A');const batches=await c.repositories.batches.listForOffering('o1');assert.equal(batches[0].status,'open');assert.equal(batches[0].committed_quantity,0);assert.equal((await c.repositories.reconciliation.inspect(created.order.id)).ok,true);assert.equal((await c.repositories.audits.list()).some(x=>x.action_type==='admin_order_cancelled'),true);c.db.close();});
test('pickup ready locks batch，complete 同步 order completed',async()=>{const c=await setup();const created=await c.orders.create('u',{communityId:'A',idempotencyKey:'pickup-001',items:[{offeringId:'o2',quantity:2}]});await c.pickups.markReady('admin','A',created.order.id);assert.equal((await c.repositories.orders.findById(created.order.id)).status,'ready_for_pickup');assert.equal((await c.repositories.batches.listForOffering('o2'))[0].status,'locked');await c.pickups.complete('admin','A',created.order.id);assert.equal((await c.repositories.orders.findById(created.order.id)).status,'completed');assert.equal((await c.repositories.pickups.findByOrderId(created.order.id)).status,'picked_up');c.db.close();});
test('unfinished order blocks leave，cancelled/completed 不阻止',async()=>{const c=await setup();const membership=new CommunityMembershipService(c.repositories);const created=await c.orders.create('u',{communityId:'A',idempotencyKey:'leave-001',items:[{offeringId:'o1',quantity:1}]});await assert.rejects(()=>membership.leave('u','A'),({code})=>code==='UNFINISHED_ORDER_OR_PICKUP');await c.orders.cancel('u',created.order.id,'不需要了');await membership.leave('u','A');assert.equal((await c.repositories.members.find('u','A')).status,'inactive');c.db.close();});
