import assert from 'node:assert/strict';
import test from 'node:test';
import { setupFulfillment } from '../helpers/fulfillment-fixture.mjs';

test('pickup APIs enforce admin scope and anti-enumeration', async()=>{const c=await setupFulfillment();try{assert.equal((await c.call('GET','/api/admin/communities/A/pickups','a')).response.status,200);assert.equal((await c.call('GET','/api/admin/communities/A/pickups','pa')).response.status,200);assert.equal((await c.call('GET','/api/admin/communities/A/pickups','u')).response.status,403);assert.equal((await c.call('GET','/api/admin/communities/A/pickups','b')).response.status,403);assert.equal((await c.call('GET','/api/admin/communities/A/pickups/missing','a')).response.status,404);assert.equal((await c.call('GET','/api/admin/communities/A/pickups/OX','a')).response.status,404);}finally{c.db.close();}});
test('cash payment uses persisted final payable and handover completes order',async()=>{const c=await setupFulfillment();try{let r=await c.call('POST','/api/admin/communities/A/pickups/O1/confirm-payment','a',{});assert.equal(r.response.status,200);assert.equal(r.json.pickup.finalPayableMinor,600);assert.equal(r.json.pickup.paymentStatus,'paid');assert.equal(c.db.database.prepare("SELECT amount_minor FROM cash_payments WHERE order_id='O1'").get().amount_minor,600);r=await c.call('POST','/api/admin/communities/A/pickups/O1/confirm-handover','a',{});assert.equal(r.json.pickup.completionState,'completed');assert.equal(c.db.database.prepare("SELECT status FROM orders WHERE id='O1'").get().status,'completed');assert.equal(/0904|confirmed_by|handed_over_by/i.test(JSON.stringify(r.json)),false);}finally{c.db.close();}});
test('handover before payment and pending procurement return 409',async()=>{const c=await setupFulfillment();try{assert.equal((await c.call('POST','/api/admin/communities/A/pickups/O1/confirm-handover','a',{})).response.status,409);assert.equal((await c.call('POST','/api/admin/communities/A/pickups/O2/confirm-payment','a',{})).response.status,409);}finally{c.db.close();}});
test('zero fulfillment is resolved with no payment or pickup required',async()=>{const c=await setupFulfillment();try{const detail=await c.call('GET','/api/admin/communities/A/pickups/O0','a');assert.equal(detail.json.pickup.completionState,'no_pickup_required');assert.equal((await c.call('POST','/api/admin/communities/A/pickups/O0/confirm-payment','a',{})).response.status,409);assert.equal((await c.call('POST','/api/admin/communities/A/pickups/O0/confirm-handover','a',{})).response.status,409);}finally{c.db.close();}});
test('client amount is rejected and inactive community historical completion works',async()=>{const c=await setupFulfillment();try{assert.equal((await c.call('POST','/api/admin/communities/A/pickups/O1/confirm-payment','a',{amount:1})).response.status,400);assert.equal((await c.call('POST','/api/admin/communities/X/pickups/OX/confirm-payment','a',{})).response.status,200);assert.equal((await c.call('POST','/api/admin/communities/X/pickups/OX/confirm-handover','a',{})).response.status,200);}finally{c.db.close();}});
test('resident order API exposes safe fulfillment projection',async()=>{const c=await setupFulfillment();try{await c.service.confirmPayment('a','A','O1');const r=await c.call('GET','/api/orders/O1','u');assert.equal(r.json.order.fulfillment.paymentStatus,'paid');assert.equal(r.json.order.fulfillment.pickupStatus,'pending');assert.equal(r.json.order.fulfillment.pickupLocation,'社區指定地點');assert.equal(/confirmed_by|handed_over_by|0904/i.test(JSON.stringify(r.json.order)),false);}finally{c.db.close();}});
test('unexpected payment database error returns safe 500',async()=>{const c=await setupFulfillment();try{c.db.exec("CREATE TRIGGER fail_payment BEFORE INSERT ON cash_payments BEGIN SELECT RAISE(ABORT,'SQL SECRET stack token'); END");const r=await c.call('POST','/api/admin/communities/A/pickups/O1/confirm-payment','a',{});assert.equal(r.response.status,500);assert.equal(/SQL|SECRET|stack|token/i.test(JSON.stringify(r.json)),false);}finally{c.db.close();}});
